package frc.team3465.omegafactor2017.cv;//package frc.team3465.omegafactor2017.cv;
//
//import edu.wpi.first.wpilibj.vision.VisionPipeline;
//import org.opencv.core.*;
//import org.opencv.features2d.FeatureDetector;
//import org.opencv.imgproc.Imgproc;
//
//import java.io.File;
//import java.io.FileWriter;
//import java.io.IOException;
//
///**
// * GripPipeline class.
// *
// * <p>An OpenCV pipeline generated by GRIP.
// *
// * @author GRIP
// */
//public class GripPipeline implements VisionPipeline {
//
//	//Outputs
//	private Mat cvFlipOutput = new Mat();
//	private Mat hslThresholdOutput = new Mat();
//	private Mat cvErodeOutput = new Mat();
//	private MatOfKeyPoint findBlobsOutput = new MatOfKeyPoint();
//
//	static {
//		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
//	}
//
//	private File tempFile;
//
//	/**
//	 * This is the primary method that runs the entire pipeline and updates the outputs.
//	 */
//	@Override	public void process(Mat source0) {
//		// Step CV_flip0:
//		Mat cvFlipSrc = source0;
//		FlipCode cvFlipFlipcode = FlipCode.X_AXIS;
//		cvFlip(cvFlipSrc, cvFlipFlipcode, cvFlipOutput);
//
//		// Step HSL_Threshold0:
//		Mat hslThresholdInput = cvFlipOutput;
//		double[] hslThresholdHue = {82.55395683453237, 107.81569965870308};
//		double[] hslThresholdSaturation = {222.43705035971223, 255.0};
//		double[] hslThresholdLuminance = {155.93525179856115, 204.95733788395904};
//		hslThreshold(hslThresholdInput, hslThresholdHue, hslThresholdSaturation, hslThresholdLuminance, hslThresholdOutput);
//
//		// Step CV_erode0:
//		Mat cvErodeSrc = hslThresholdOutput;
//		//cvEro= null;
//		Mat cvErodeKernel = new Mat();
//		Point cvErodeAnchor = new Point(-1, -1);
//		double cvErodeIterations = 1.0;
//		int cvErodeBordertype = Core.BORDER_CONSTANT;
//		Scalar cvErodeBordervalue = new Scalar(-1);
//		cvErode(cvErodeSrc, cvErodeKernel, cvErodeAnchor, cvErodeIterations, cvErodeBordertype, cvErodeBordervalue, cvErodeOutput);
//        cvErodeKernel = null;
//
//		// Step Find_Blobs0:
//		Mat findBlobsInput = cvErodeOutput;
//		double findBlobsMinArea = 40.0;
//		double[] findBlobsCircularity = {0.0, 1.0};
//		boolean findBlobsDarkBlobs = false;
//		findBlobs(findBlobsInput, findBlobsMinArea, findBlobsCircularity, findBlobsDarkBlobs, findBlobsOutput);
//
//	}
//
//	/**
//	 * This method is a generated getter for the output of a CV_flip.
//	 * @return Mat output from CV_flip.
//	 */
//	public Mat cvFlipOutput() {
//		return cvFlipOutput;
//	}
//
//	/**
//	 * This method is a generated getter for the output of a HSL_Threshold.
//	 * @return Mat output from HSL_Threshold.
//	 */
//	public Mat hslThresholdOutput() {
//		return hslThresholdOutput;
//	}
//
//	/**
//	 * This method is a generated getter for the output of a CV_erode.
//	 * @return Mat output from CV_erode.
//	 */
//	public Mat cvErodeOutput() {
//		return cvErodeOutput;
//	}
//
//	/**
//	 * This method is a generated getter for the output of a Find_Blobs.
//	 * @return MatOfKeyPoint output from Find_Blobs.
//	 */
//	public MatOfKeyPoint findBlobsOutput() {
//		return findBlobsOutput;
//	}
//
//
//	/**
//	 * Code used for CV_flip.
//	 * Per OpenCV spec 0 -> flip on X axis.
//	 * >0 -> flip on Y axis.
//	 * <0 -> flip on both axes.
//	 */
//	public enum FlipCode {
//		X_AXIS(0),
//		Y_AXIS(1),
//		BOTH_AXES(-1);
//		public final int value;
//		FlipCode(int value) {
//			this.value = value;
//		}
//	}
//
//	/**
//	 * Flips an image along X, Y or both axes.
//	 * @param src Image to flip.
//	 * @param flipcode FlipCode of which direction to flip.
//	 * @param dst flipped version of the Image.
//	 */
//	private void cvFlip(Mat src, FlipCode flipcode, Mat dst) {
//		Core.flip(src, dst, flipcode.value);
//	}
//
//	/**
//	 * Segment an image based on hue, saturation, and luminance ranges.
//	 *
//	 * @param input The image on which to perform the HSL threshold.
//	 * @param hue The min and max hue
//	 * @param sat The min and max saturation
//	 * @param lum The min and max luminance
//	 * @param out The image in which to store the output.
//	 */
//	private void hslThreshold(Mat input, double[] hue, double[] sat, double[] lum,
//							  Mat out) {
//		Imgproc.cvtColor(input, out, Imgproc.COLOR_BGR2HLS);
//		Core.inRange(out, new Scalar(hue[0], lum[0], sat[0]),
//				new Scalar(hue[1], lum[1], sat[1]), out);
//	}
//
//	/**
//	 * Expands area of lower value in an image.
//	 * @param src the Image to erode.
//	 * @param kernel the kernel for erosion.
//	 * @param anchor the center of the kernel.
//	 * @param iterations the number of times to perform the erosion.
//	 * @param borderType pixel extrapolation method.
//	 * @param borderValue value to be used for a constant border.
//	 * @param dst Output Image.
//	 */
//	private void cvErode(Mat src, Mat kernel, Point anchor, double iterations,
//						 int borderType, Scalar borderValue, Mat dst) {
//		if (kernel == null) {
//			kernel = new Mat();
//		}
//		if (anchor == null) {
//			anchor = new Point(-1,-1);
//		}
//		if (borderValue == null) {
//			borderValue = new Scalar(-1);
//		}
//		Imgproc.erode(src, dst, kernel, anchor, (int)iterations, borderType, borderValue);
//	}
//
//	/**
//	 * Detects groups of pixels in an image.
//	 * @param input The image on which to perform the find blobs.
//	 * @param minArea The minimum size of a blob that will be found
//	 * @param circularity The minimum and maximum circularity of blobs that will be found
//	 * @param darkBlobs The boolean that determines if light or dark blobs are found.
//	 * @param blobList The output where the MatOfKeyPoint is stored.
//	 */
//	private void findBlobs(Mat input, double minArea, double[] circularity,
//						   Boolean darkBlobs, MatOfKeyPoint blobList) {
//		FeatureDetector blobDet = FeatureDetector.create(FeatureDetector.SIMPLEBLOB);
//		try {
//			if (tempFile == null) {
//				tempFile = File.createTempFile("config", ".xml");
//
//				StringBuilder config = new StringBuilder();
//
//				config.append("<?xml version=\"1.0\"?>\n");
//				config.append("<opencv_storage>\n");
//				config.append("<thresholdStep>10.</thresholdStep>\n");
//				config.append("<minThreshold>50.</minThreshold>\n");
//				config.append("<maxThreshold>220.</maxThreshold>\n");
//				config.append("<minRepeatability>2</minRepeatability>\n");
//				config.append("<minDistBetweenBlobs>10.</minDistBetweenBlobs>\n");
//				config.append("<filterByColor>1</filterByColor>\n");
//				config.append("<blobColor>");
//				config.append((darkBlobs ? 0 : 255));
//				config.append("</blobColor>\n");
//				config.append("<filterByArea>1</filterByArea>\n");
//				config.append("<minArea>");
//				config.append(minArea);
//				config.append("</minArea>\n");
//				config.append("<maxArea>");
//				config.append(Integer.MAX_VALUE);
//				config.append("</maxArea>\n");
//				config.append("<filterByCircularity>1</filterByCircularity>\n");
//				config.append("<minCircularity>");
//				config.append(circularity[0]);
//				config.append("</minCircularity>\n");
//				config.append("<maxCircularity>");
//				config.append(circularity[1]);
//				config.append("</maxCircularity>\n");
//				config.append("<filterByInertia>1</filterByInertia>\n");
//				config.append("<minInertiaRatio>0.1</minInertiaRatio>\n");
//				config.append("<maxInertiaRatio>" + Integer.MAX_VALUE + "</maxInertiaRatio>\n");
//				config.append("<filterByConvexity>1</filterByConvexity>\n");
//				config.append("<minConvexity>0.95</minConvexity>\n");
//				config.append("<maxConvexity>" + Integer.MAX_VALUE + "</maxConvexity>\n");
//				config.append("</opencv_storage>\n");
//				FileWriter writer;
//				writer = new FileWriter(tempFile, false);
//				writer.write(config.toString());
//				writer.close();
//			}
//			blobDet.read(tempFile.getPath());
//		} catch (IOException e) {
//			e.printStackTrace();
//		}
//
//		blobDet.detect(input, blobList);
//	}
//}
//
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.HashMap;

import edu.wpi.first.wpilibj.vision.VisionPipeline;

import org.opencv.core.*;
import org.opencv.core.Core.*;
import org.opencv.features2d.FeatureDetector;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.*;
import org.opencv.objdetect.*;

/**
 * GripPipeline class.
 *
 * <p>An OpenCV pipeline generated by GRIP.
 *
 * @author GRIP
 */
public class GripPipeline implements VisionPipeline {

	//Outputs
	private Mat cvFlipOutput = new Mat();
	private Mat hslThresholdOutput = new Mat();
	private Mat cvErodeOutput = new Mat();
	private MatOfKeyPoint findBlobsOutput = new MatOfKeyPoint();

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	private File tempFile;

	/**
	 * This is the primary method that runs the entire pipeline and updates the outputs.
	 */
	@Override	public void process(Mat source0) {
		// Step CV_flip0:
		Mat cvFlipSrc = source0;
		FlipCode cvFlipFlipcode = FlipCode.X_AXIS;
		cvFlip(cvFlipSrc, cvFlipFlipcode, cvFlipOutput);

		// Step HSL_Threshold0:
		Mat hslThresholdInput = cvFlipOutput;
		double[] hslThresholdHue = {59.91113661918027, 89.61465025878046};
		double[] hslThresholdSaturation = {220.34081564081046, 254.73829765519892};
		double[] hslThresholdLuminance = {128.1805254555737, 255.0};
		hslThreshold(hslThresholdInput, hslThresholdHue, hslThresholdSaturation, hslThresholdLuminance, hslThresholdOutput);

		// Step CV_erode0:
		Mat cvErodeSrc = hslThresholdOutput;
		Mat cvErodeKernel = new Mat();
		Point cvErodeAnchor = new Point(-1, -1);
		double cvErodeIterations = 2.0;
		int cvErodeBordertype = Core.BORDER_CONSTANT;
		Scalar cvErodeBordervalue = new Scalar(-1);
		cvErode(cvErodeSrc, cvErodeKernel, cvErodeAnchor, cvErodeIterations, cvErodeBordertype, cvErodeBordervalue, cvErodeOutput);

		// Step Find_Blobs0:
		Mat findBlobsInput = cvErodeOutput;
		double findBlobsMinArea = 60.0;
		double[] findBlobsCircularity = {0.0, 1.0};
		boolean findBlobsDarkBlobs = false;
		findBlobs(findBlobsInput, findBlobsMinArea, findBlobsCircularity, findBlobsDarkBlobs, findBlobsOutput);

	}

	/**
	 * This method is a generated getter for the output of a CV_flip.
	 * @return Mat output from CV_flip.
	 */
	public Mat cvFlipOutput() {
		return cvFlipOutput;
	}

	/**
	 * This method is a generated getter for the output of a HSL_Threshold.
	 * @return Mat output from HSL_Threshold.
	 */
	public Mat hslThresholdOutput() {
		return hslThresholdOutput;
	}

	/**
	 * This method is a generated getter for the output of a CV_erode.
	 * @return Mat output from CV_erode.
	 */
	public Mat cvErodeOutput() {
		return cvErodeOutput;
	}

	/**
	 * This method is a generated getter for the output of a Find_Blobs.
	 * @return MatOfKeyPoint output from Find_Blobs.
	 */
	public MatOfKeyPoint findBlobsOutput() {
		return findBlobsOutput;
	}


	/**
	 * Code used for CV_flip.
	 * Per OpenCV spec 0 -> flip on X axis.
	 * >0 -> flip on Y axis.
	 * <0 -> flip on both axes.
	 */
	public enum FlipCode {
		X_AXIS(0),
		Y_AXIS(1),
		BOTH_AXES(-1);
		public final int value;
		FlipCode(int value) {
			this.value = value;
		}
	}

	/**
	 * Flips an image along X, Y or both axes.
	 * @param src Image to flip.
	 * @param flipcode FlipCode of which direction to flip.
	 * @param dst flipped version of the Image.
	 */
	private void cvFlip(Mat src, FlipCode flipcode, Mat dst) {
		Core.flip(src, dst, flipcode.value);
	}

	/**
	 * Segment an image based on hue, saturation, and luminance ranges.
	 *
	 * @param input The image on which to perform the HSL threshold.
	 * @param hue The min and max hue
	 * @param sat The min and max saturation
	 * @param lum The min and max luminance
	 * @param output The image in which to store the output.
	 */
	private void hslThreshold(Mat input, double[] hue, double[] sat, double[] lum,
							  Mat out) {
		Imgproc.cvtColor(input, out, Imgproc.COLOR_BGR2HLS);
		Core.inRange(out, new Scalar(hue[0], lum[0], sat[0]),
				new Scalar(hue[1], lum[1], sat[1]), out);
	}

	/**
	 * Expands area of lower value in an image.
	 * @param src the Image to erode.
	 * @param kernel the kernel for erosion.
	 * @param anchor the center of the kernel.
	 * @param iterations the number of times to perform the erosion.
	 * @param borderType pixel extrapolation method.
	 * @param borderValue value to be used for a constant border.
	 * @param dst Output Image.
	 */
	private void cvErode(Mat src, Mat kernel, Point anchor, double iterations,
						 int borderType, Scalar borderValue, Mat dst) {
		if (kernel == null) {
			kernel = new Mat();
		}
		if (anchor == null) {
			anchor = new Point(-1,-1);
		}
		if (borderValue == null) {
			borderValue = new Scalar(-1);
		}
		Imgproc.erode(src, dst, kernel, anchor, (int)iterations, borderType, borderValue);
	}

	/**
	 * Detects groups of pixels in an image.
	 * @param input The image on which to perform the find blobs.
	 * @param minArea The minimum size of a blob that will be found
	 * @param circularity The minimum and maximum circularity of blobs that will be found
	 * @param darkBlobs The boolean that determines if light or dark blobs are found.
	 * @param blobList The output where the MatOfKeyPoint is stored.
	 */
	private void findBlobs(Mat input, double minArea, double[] circularity,
						   Boolean darkBlobs, MatOfKeyPoint blobList) {
		FeatureDetector blobDet = FeatureDetector.create(FeatureDetector.SIMPLEBLOB);
		try {
			if (tempFile == null) {
				tempFile = File.createTempFile("config", ".xml");

				StringBuilder config = new StringBuilder();

				config.append("<?xml version=\"1.0\"?>\n");
				config.append("<opencv_storage>\n");
				config.append("<thresholdStep>10.</thresholdStep>\n");
				config.append("<minThreshold>50.</minThreshold>\n");
				config.append("<maxThreshold>220.</maxThreshold>\n");
				config.append("<minRepeatability>2</minRepeatability>\n");
				config.append("<minDistBetweenBlobs>10.</minDistBetweenBlobs>\n");
				config.append("<filterByColor>1</filterByColor>\n");
				config.append("<blobColor>");
				config.append((darkBlobs ? 0 : 255));
				config.append("</blobColor>\n");
				config.append("<filterByArea>1</filterByArea>\n");
				config.append("<minArea>");
				config.append(minArea);
				config.append("</minArea>\n");
				config.append("<maxArea>");
				config.append(Integer.MAX_VALUE);
				config.append("</maxArea>\n");
				config.append("<filterByCircularity>1</filterByCircularity>\n");
				config.append("<minCircularity>");
				config.append(circularity[0]);
				config.append("</minCircularity>\n");
				config.append("<maxCircularity>");
				config.append(circularity[1]);
				config.append("</maxCircularity>\n");
				config.append("<filterByInertia>1</filterByInertia>\n");
				config.append("<minInertiaRatio>0.1</minInertiaRatio>\n");
				config.append("<maxInertiaRatio>" + Integer.MAX_VALUE + "</maxInertiaRatio>\n");
				config.append("<filterByConvexity>1</filterByConvexity>\n");
				config.append("<minConvexity>0.95</minConvexity>\n");
				config.append("<maxConvexity>" + Integer.MAX_VALUE + "</maxConvexity>\n");
				config.append("</opencv_storage>\n");
				FileWriter writer;
				writer = new FileWriter(tempFile, false);
				writer.write(config.toString());
				writer.close();
			}
			blobDet.read(tempFile.getPath());
		} catch (IOException e) {
			e.printStackTrace();
		}

		blobDet.detect(input, blobList);
	}




}

